@HostAddress = https://localhost:7039

GET {{HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{HostAddress}}/api/customers?pageSize=20
Accept: application/json

###

GET {{HostAddress}}/api/customers?pageSize=20&cursor=MjA=
Accept: application/json

###
